### GET
GET http://localhost:3000/todo?page=5
Accept: application/json

### GET BY ID
GET http://localhost:3000/todo/2
Accept: application/json

### GET v2
GET http://localhost:3000/todo/v2
Accept: application/json

### POST
POST http://localhost:3000/todo
Content-Type: application/json
Accept: application/json

{
  "name": "2ème TODO",
  "description": "Deuxième TODO"
}

### DELETE
DELETE http://localhost:3000/todo/1
Accept: application/json

### PUT
PUT http://localhost:3000/todo/4
Content-Type: application/json
Accept: application/json

  {
    "name": "Second TODO3",
    "description": "second description"
  }

